### PR TITLE
fix AssetEntityImageProvider asset thumbSize length error , when previewThumbSize is null

### PR DESCRIPTION
**Pull request by JasonHezz**

### CODE REVIEW

**Comment by AlexV525** [comment]
In which cases this can be null?

**Comment by JasonHezz** [comment]
click image and navigate to preview page
image

image

**Comment by AlexV525** [comment]
Confirmed, but I'll fix this in another way. I'll notify you once it's done. Thanks for this fix!

**Comment by AlexV525** [comment]
Can you try with the commit I've linked to see if it's fixed?

**Comment by JasonHezz** [comment]
> Can you try with the commit I've linked to see if it's fixed?

Yep, work as expected, can you release a new version?

**Comment by AlexV525** [comment]
> Yep, work as expected, can you release a new version?

On it.

**Pull request closed without merging**
