### PR TITLE
♻️ Split `AssetGridItemBuilder` to solve the rebuild issue

### LINKED ISSUE #127: [Optimize scrolling] Scrolling of grid shows black/empty items
Problem description:
When scrolling the grid, it happens very often that all the grid items become black, and then they are repopulated. It's a very bad experience for the user. It happens even when using very low resolution for the grid items.

Optimization suggestion:
Consider replacing the `GridView.builder` with `SliverGrid` with `SliverChildBuilderDelegate` that has `findChildIndexCallback`.
It is most likely that it will improve performance of scrolling.

If that direction sounds ok to you, I will be happy to try it and submit a PR.
If you have other thought, please share.

Thanks,
Yaniv

### PR DESCRIPTION
**Pull request by AlexV525**
Resolves #127 .

This is a minimum solution to solve the issue directly, without any breaking changes.

### CODE REVIEW

**Comment by AlexV525** [comment]
Actually the `loadMoreAssets` method didn't called multiple times.

```
I/flutter (25101): Loading more assets with page 1: 2021-05-11 11:59:40.085985
I/flutter (25101): Loading more assets with page 2: 2021-05-11 11:59:42.464812
I/flutter (25101): Loading more assets with page 3: 2021-05-11 11:59:44.597433
I/flutter (25101): Loading more assets with page 4: 2021-05-11 11:59:47.431908
I/flutter (25101): Loading more assets with page 5: 2021-05-11 11:59:49.276166
I/flutter (25101): Loading more assets with page 6: 2021-05-11 11:59:52.039088
```

**Comment by yanivshaked** [comment]
Testing

**Comment by yanivshaked** [comment]
Look good.
In term of performance, it is better to use `SliverGrid` instead of `GridView.builder`.
The reason for that is that when the grid has to repaint itself, you can "teach" the `SliverGrid` how to find the elements from the previously painted grid using `findChildIndexCallback`. That cannot be done in the case of `GridView.builder` (which is specific implementation of `SliverGrid`).

See:
https://stackoverflow.com/a/58991316/6535274

https://medium.com/flutter/slivers-demystified-6ff68ab0296f

**Comment by AlexV525** [comment]
Take another look.

**Comment by yanivshaked** [comment]
I am contantly checking :-)

While performance is better scrolling down (due to `findChildIndexCallback`), there is now an issue when scrolling up (that did NOT exist with `GridView.builder`).
Scrolling up shows black grid items for a moment.

**Comment by AlexV525** [comment]
> previous experience was better.

"Previous" only indicates the commit in this PR. Originally it does act like that too. The automatic keepalives flag isn't the same thing as a Widget does itself.

**Comment by yanivshaked** [comment]
Correct, that is what I meant. Previous = after the split.

**Comment by AlexV525** [comment]
Going deeper, it's some GC trick that came from `extended_image`. So for now I would not recommend to commit that behavior.

**Comment by yanivshaked** [comment]
I agree, better go back to `GridView.builder`.

**Comment by yanivshaked** [comment]
The tradeoff of optimize memory save optimize speed will always be there.
Is there some way to preload the assets in the `SliverGrid` case so that it will be less visible to the user?

**Comment by AlexV525** [comment]
Have you registered with Discord? You can add me `Alex Li (AlexV525)#3670` then we can discuss about this.

**Comment by yanivshaked** [comment]
Friend request sent

**Pull request merged**
