### PR TITLE
Add support to filter lists with a custom function

### PR DESCRIPTION
**Pull request by daentech**
A feature I was missing was to be able to filter the list of assets by mime type as we only support specific video file types. I could have created a custom builder and provider, but the simpler solution seemed to be to provide it within the `DefaultAssetPickerProvider`

There is the `selectPredicate` however that just means you can't select an item and there is no feedback to the user for why it couldn't be selected.

This PR changes the Picker config to take in a custom function which can be used to filter the output list to not show undesired assets in the first place. In the example I'm using the mime type, but any other function returning a bool would work.

The only thing I'm not certain about is that currently in the `AssetPickerConfig` the function is currently untyped/dynamic as it doesn't get the type from the `DefaultAssetPickerBuilderDelegate` at that level, so there was some casting involved. Maybe there is a better solution to that

### CODE REVIEW

**Comment by AlexV525** [comment]
I don't feel it's the right way. The most efficient improvement would be to support filtering assets with MIME types. Though we need more investigations if we want to do so.

**Comment by daentech** [comment]
Filtering by mime type would be very helpful for us. I was considering just passing in a list of them (either black or whitelist) and handling it internally.

A simpler improvement in the interim would be to show some kind of message to the user when they attempt to select something which the selectPredicate forbids. Would that be possible?

**Comment by AlexV525** [comment]
> A simpler improvement in the interim would be to show some kind of message to the user when they attempt to select something which the selectPredicate forbids. Would that be possible?

That's is totally implementable, since you can write your own method, like `showToast` when predicating. You can simply write your code in the predication to achieve the goal.

Regarding the PR, it's not completed yet. It only handles the assets, but not involved with paginations. This is a common cases when users eant to customize their own filtering, and basically they will end up with a complete mess (so do I). It's still better to filtering fromthe source, rather than the endpoint.

Based on the above opinion, I'm going to draft this PR. Feel free to continue your work if you have better idea later, and feel free to close if it's too complicated. Also, you can submit an issue to the `photo_manager` repo to track whether we can implement MIME types as a filtering option.

**Comment by daentech** [comment]
Got it, thanks. I'll take a look!

**Comment by daentech** [comment]
I've taken a look and you're right. I hadn't considered pagination (I hadn't hit it on my test devices). I'm going to go with showing a toast (I had tried showing a snackbar previously but there wasn't a Scaffold available) for the moment and I'll take a look at photo_manager and see if I can propose something for mime type filtering in there.

Thanks!

**Pull request closed without merging**
