### PR TITLE
✨ UI Enhancement: Support for RTL languages

### PR DESCRIPTION
**Pull request by yanivshaked**
- Changes to support RTL languages.
- Added a space to seprate between the confirm text and the numbers

### CODE REVIEW

**Comment by AlexV525** [comment]
Why we don't use `Directionality.of` here?

**Comment by yanivshaked** [comment]
How can `Directionality.of` help here?
The idea is that the `FixedAppBar` layout will be according to the active language.
In addition, since the folder name selection widget presents folder names, fix it so that LTR is always used there.
I have tested on both LTR and RTL languages:
image

image

**Comment by AlexV525** [comment]
IMO in a hebrew app, for example, you'll define a global text direction in you `WidgetsApp` (MaterialApp), then the direction will be passed through the tree. So if a hebrew app should be RTL, it'll applied to the app, without extra specified.

**Comment by yanivshaked** [comment]
I have integrated this asset picker as the main asset for Megatok.
I'm using AssetPicker.pickAssets; How can I pass the direcionality to the picker?

**Comment by AlexV525** [comment]
There's no need to pass. They all came across though context, AKA widget tree. You might want to take a look a the `of` method. I'll make an instruction if I have spare time.

**Comment by yanivshaked** [comment]
I know the use of `of` statement, but if it requires that the asset picker will make use of it.
Still there is the issue of the `pathEntitySelector`, how can that be controlled if no changes are incorporated?

**Comment by AlexV525** [comment]
It should be change, but there's no need for the text direction defined in the delegate.

image

**Comment by AlexV525** [comment]
Let me take care of it. This should be implemented in more places that you defined here. I'll file a PR once it's ready. Thanks.

**Pull request closed without merging**
