### PR TITLE
ru translation for semantics fields

### PR DESCRIPTION
**Pull request by greymag**
See #239

### CODE REVIEW

**Comment by AlexV525** [comment]
Thanks for the rapid update! Though I suggest you try with the Talkback and see if they are correct in their scenarios.

**Comment by greymag** [comment]
I didn't try it, but I read the code and translate strings according to the represented action. I can try with the Talkback on Monday.

**Comment by AlexV525** [comment]
> I can try with the Talkback on Monday.

I'll wait for your feedback and confirm then.

**Comment by AlexV525** [comment]
(friendly ping @greymag)

**Comment by greymag** [comment]
Just finished checking with Talkback. Made one fix.

**Pull request merged**
