### PR TITLE
🐛 Further fix to the wrong behavior in WeChat Moment video preview

### PR DESCRIPTION
**Pull request by AlexV525**
Further fix to #110 .

cc @yanivshaked

### CODE REVIEW

**Review by yanivshaked — COMMENTED** [review]
Better experience to use clamping physics 👍

**Comment by yanivshaked** [comment]
All changes are ok, but one more bug - you need to initialize the state of the picker when started with selected assets:
- Example -> Multi -> WeChatMoment Picker
- Click on a video to have its preview, then click confirm to have it selected. You are out of the picker now.
- Click the WeChatMoment picker again to have extra assets selected (you start with selected assets).
- You can now select images in addition to the preselected video.

**Comment by AlexV525** [comment]
Yeah this is really an edge case since the WeChat Moment don't have that kind of interaction like our demo does.

**Review by yanivshaked — APPROVED** [review]
I think the edge case should be covered

**Comment by AlexV525** [comment]
Double checked the behavior in WeChat, it's seems selected assets is not passed when re-enter the picker. I think simply remove selected assets passing in the WeChat Moment type should be okay.

https://user-images.githubusercontent.com/15884415/116776888-ab922080-aa9d-11eb-91f0-565699b677b0.mp4

**Review by yanivshaked — COMMENTED** [review]
You might want to enforce it in pickAssets when specialPickerType is wechatMoment.

**Comment by AlexV525** [comment]
I personally think it's unneeded. The point I exposed the `selectedAssets` field is to provide the ability that developers can determine whether they need previous assets or not.

**Comment by yanivshaked** [comment]
Using `selectedAssets` allows the user to add more assets to the selection in case he missed something. I agree than for wechatMoment it is less relevant. It's up to you :-)

**Comment by AlexV525** [comment]
I will postpone it a bit to release it to the next version, need to take a break because we are currently on Labor Day holiday.

**Comment by yanivshaked** [comment]
Enjoy the holiday!

**Pull request merged**
