### PR TITLE
🐛 Fix Wechat Moment preview issue

### LINKED ISSUE #110: [BUG] Ability to choose both video and image in SpecialPickerType.wechatMoment
**Bug description**
When using SpecialPickerType.wechatMoment, I am able to select both image and video files.
I made sure that this bug is NOT related to the noPreview changes.

**How to reproduce**
- Run the example
- Click Single Asset picker page
- Click WeChat moment
- Click on an image to get its preview
- Select it using the "Select" button at the bottom bar
- Swipe right till you get a video asset
- Select it using the "Select" button at the bottom bar
- Click done

**Expected behavior**
Should not allow selection of video if image is already selected (and vice versa).

**Screenshots (If contains)**
If needed, I can upload a video.

**Device information**
 - Device: Android OnePlus 8T
 - OS: Android 10
 - Package Version: 5.1.3 or 5.2.0 (reproduced on both)
 - Flutter Version: 2.0.5

**Additional context**
Let me know what are your thoughts on solving this, I can submit a PR.

### PR DESCRIPTION
**Pull request by AlexV525**
Resolves #110 .

cc @yanivshaked

### CODE REVIEW

**Review by yanivshaked — APPROVED** [review]
Great, it should have been in multi assets page.

**Comment by yanivshaked** [comment]
While testing, I found the following scenario:
- Open example with WeChatMoment picker type
- Click a video to preview it
- Click the select button at the bottom
- Click back to go back to the grid
- Click an image selector to have it selected
- Now you have two assets selected - one is a video the 2nd is an image (The app bar says 2/9)

**Comment by AlexV525** [comment]
Sounds like we need to disabled the bottom select button when previewing the video in the WeChat Moment picker type.

**Comment by yanivshaked** [comment]
Correct, that will solve the issue.

**Pull request merged**
