### PR TITLE
✨ Support RTL

### PR DESCRIPTION
**Pull request by AlexV525**
* `EdgeInsets` -> `EdgeInsetsDirectional`
* `Positioned` -> `PositionedDirectional`
* Some other RTL fit changes.

cc @yanivshaked Take a look.

### CODE REVIEW

**Comment by AlexV525** [comment]
To turn on the RTL layout, pass `Locale('iw')` to your `WidgetsApp`/`MaterialApp`/`CupertinoApp`.

**Comment by yanivshaked** [comment]
Testing it now

**Comment by yanivshaked** [comment]
> To turn on the RTL layout, pass `Locale('iw')` to your `WidgetsApp`/`MaterialApp`/`CupertinoApp`.

To test it, I have added `locale` to the main example file:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'WeChat Asset Picker Demo',
      theme: ThemeData(
        brightness: Screens.mediaQuery.platformBrightness,
        primarySwatch: themeColor.swatch,
        textSelectionTheme: const TextSelectionThemeData(
          cursorColor: themeColor,
        ),
      ),
      home: const SplashPage(),
      builder: (BuildContext c, Widget? w) {
        return ScrollConfiguration(
          behavior: const NoGlowScrollBehavior(),
          child: w!,
        );
      },
      locale: const Locale('iw'),
    );
  }
}
```

But there is no impact on the layout.

**Comment by AlexV525** [comment]
Check what demo does.

**Comment by yanivshaked** [comment]
Works great, thank you!

**Pull request merged**
