### PR TITLE
Fix index error on selectedBackdrop

### PR DESCRIPTION
**Pull request by ConanXie**

### CODE REVIEW

**Comment by AlexV525** [comment]
Thanks for the fix. Can you provide screenshots that indicate before and after the fix?

**Comment by ConanXie** [comment]
If you run the example app, then open then picker from `Pick from camera` and then click on a picture to view it, you will find it always views the next one.

Because the `index` *(pass to `selectedBackdrop`)* needs to be subtracted by 1 when there is `SpecialItemPosition.prepend`, and using the `currentIndex` is correct.

**Review by AlexV525 — APPROVED** [review]
LGTM

**Comment by AlexV525** [comment]
@all-contributors Add @ConanXie for bugs.

**Pull request merged**
