### PR TITLE
Semantics with Vietnamese

### PR DESCRIPTION
**Pull request by nploi**
Hi team, 
I want support Vietnamese language for this package, please review it. 
Thank you.

### CODE REVIEW

**Comment by nploi** [comment]
hi @AlexV525 can you help review this one ? thank you!

**Comment by AlexV525** [comment]
@nploi Thanks for the new language support. Generally adding language support will require providing a screen record with TalkBack or VoiceOver enabled to see if those fields play well in the accessibility mode.

**Comment by nploi** [comment]
> @nploi Thanks for the new language support. Generally adding language support will require providing a screen record with TalkBack or VoiceOver enabled to see if those fields play well in the accessibility mode.

okay, i will update that soon.

**Comment by nploi** [comment]
Hi @AlexV525, i have a short record with TalkBack.

https://user-images.githubusercontent.com/34020090/233710754-ac55403f-1a80-4324-9dba-5ba6771aff18.mp4

**Comment by AlexV525** [comment]
The text delegate and the semantics LGTM. Please also add a CHANGELOG entry and update the pubspec too.

**Comment by nploi** [comment]
> The text delegate and the semantics LGTM. Please also add a CHANGELOG entry and update the pubspec too.

Done @AlexV525.

**Review by AlexV525 — APPROVED** [review]

**Comment by AlexV525** [comment]
@all-contributors Add @nploi for internationalization.

**Comment by AlexV525** [comment]
@all-contributors Add @nploi for translation.

**Pull request merged**
