### PR TITLE
⚡️ Split assets fetching into separate steps

### LINKED ISSUE #496: [BUG] iOS相册中有 33,450张照片、1,660个视频。 选择图片时，一直显示加载中。
**Describe the bug**

相册中有 33,450张照片、1,660个视频。(有 icloud 照片)
选择图片时，一直显示加载中。

**How to reproduce**

```
    final List<AssetEntity>? result = await AssetPicker.pickAssets(context,
        pickerConfig: AssetPickerConfig(
          requestType: RequestType.image,
          filterOptions: FilterOptionGroup(containsLivePhotos: true),
          limitedPermissionOverlayPredicate: limitedPermissionOverlayPredicate,
        ));
```

直接点击，选择照片

**Expected behavior**

能正常加载并选择图片

**Screenshots (If contains)**

image

**Version information**

- Device: [e.g. iPhone X] iPhone 13
- OS: [e.g. iOS 14.7.1] iOS 16.6
- Package Version: wechat_assets_picker: ^8.6.3  photo_manager: ^2.7.1
- Flutter Version: [e.g. v2.5.0] v3.10.1

**Additional context**

### LINKED ISSUE #526: 一加ACEP 16G运行内存，3万多张图片，加载了6-7秒出来网格
一加ACEP 16G运行内存，3万多张图片，加载了6-7秒出来

这种正常吗，我看21年的时候也有一个类似的问题
https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/116

还有没有什么好的优化的方法，
demo里面的通过降低缩略图质量的方法，也只能提高不到1秒。快6秒加载出来。

### LINKED ISSUE #547: [BUG] 部分机型读取图片列表加载过慢，8600多个图片，加载总耗时30S
**Describe the bug**

 荣耀20PRO手机内总有8600多张图片，在读取图片列表时，一直在loading转圈，总耗时30秒左右，代码如下：
  assets_picker耗时
而另一个手机mate60，内有369张图片，加载不到1秒，视频已发在群里，代码位置：
image

**How to reproduce**

1. 点击图片选择
2. 进入图片选择列表，一直在Loading加载图片

**Expected behavior**

能正常速度加载并选择图片
**Screenshots (If contains)**

WechatIMG36

**Version information**

- Device: 荣耀20 PRO、Mate60
- OS: Harmony os 3和4
- Package Version:   wechat_assets_picker: ^8.9.0-dev.1    photo_manager: ^3.0.0-dev.1
- Flutter Version: 3.16.0

**Additional context**

### PR DESCRIPTION
**Pull request by AlexV525**
### Changes
1. Change the fetching steps to loading the first album first, then the others.
2. Use `AdvancedCustomFilter` by default to order items in desc without extra search queries to decrease the query complexity.

- Resolves #496
- Resolves #526
- Resolves #547

### CODE REVIEW

**Comment by HongZhiQing** [comment]
Does version 9.1.0 include this?

**Comment by DavidChZh** [comment]
> 9.1.0 版本包含这个吗？

包含

**Comment by DavidChZh** [comment]
> Does version 9.1.0 include this?

include

**Comment by bladeofgod** [comment]
it worked , nice !

**Comment by himotou** [comment]
> 这个问题在9.8.0版本上还有出现需要调整什么配置吗

你试试低版本有没有问题，也可能跟这个不是一个问题，如果低版本也有问题就得具体问题具体分析了。

**Pull request merged**
